"""ESG / Scope 2 sustainability report PDF generation."""

from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from fpdf import FPDF

from sim_environment.grid_data import REGIONS


def _ascii(text: str) -> str:
    """fpdf2 Helvetica is Latin-1 only — strip subscripts and non-ASCII chars."""
    return (
        text.replace("gCO₂", "gCO2")
        .replace("CO₂", "CO2")
        .replace("₂", "2")
        .encode("ascii", errors="replace")
        .decode("ascii")
    )


class ESGReportPDF(FPDF):
    def header(self) -> None:
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, "EcoRouter ESG Report - Scope 2 Compute Emissions", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def section(self, title: str) -> None:
        self.set_font("Helvetica", "B", 10)
        self.set_fill_color(240, 253, 244)
        self.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT", fill=True)
        self.ln(1)

    def body(self, text: str) -> None:
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 5, _ascii(text))
        self.ln(1)


def generate_esg_pdf(
    jobs: list[dict[str, Any]],
    grid_status: dict[str, int],
    assignments: list[dict[str, Any]],
    comparison: dict[str, Any] | None,
    grid_source: str,
    router: str,
    tariffs: dict[str, float] | None = None,
) -> bytes:
    """Build a downloadable ESG PDF report for sustainability / compliance teams."""
    pdf = ESGReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pdf.body(f"Generated: {now}\nRouting engine: {router}\nGrid data source: {grid_source}")

    pdf.section("Executive Summary")
    if comparison:
        pdf.body(
            f"EcoRouter routed {len(assignments)} workloads with an estimated "
            f"{comparison['carbon_saved_gco2']:,} gCO2 avoided ({comparison['savings_pct']}%) "
            f"versus {comparison['baseline_name']}.\n"
            f"Energy cost savings: ${comparison['cost_saved_usd']:.2f} "
            f"({comparison['cost_savings_pct']}%) vs baseline.\n"
            f"EcoRouter total: {comparison['eco_total_gco2']:,} gCO2 / "
            f"${comparison['eco_total_cost_usd']:.2f}.\n"
            f"Baseline total: {comparison['baseline_total_gco2']:,} gCO2 / "
            f"${comparison['baseline_total_cost_usd']:.2f}."
        )
    else:
        pdf.body(f"{len(assignments)} workloads routed. Run A/B comparison for savings metrics.")

    pdf.section("Grid Telemetry (gCO2/kWh)")
    for region in REGIONS:
        pdf.body(f"  {region}: {grid_status.get(region, 'N/A')}")

    pdf.section("Workload Assignments")
    by_job = {a["job_id"]: a for a in assignments}
    for job in jobs:
        a = by_job.get(job["job_id"])
        if not a:
            continue
        region = a["target_region"]
        carbon = grid_status.get(region, 0) * job["compute_hours"]
        sla = "PASS" if a.get("sla_met", True) else "FAIL"
        pdf.body(
            f"- {job['task']} ({job['job_id']})\n"
            f"  Region: {region} | Carbon: {carbon:,} gCO2 | SLA: {sla}\n"
            f"  Deadline: {job.get('deadline_utc', 'N/A')}\n"
            f"  {a.get('reasoning', '')[:120]}"
        )

    pdf.section("Methodology")
    pdf.body(
        "Carbon estimate = regional grid intensity (gCO2/kWh) x compute hours. "
        "Cost estimate = regional tariff (USD/kWh) x compute hours. "
        "Figures are modeled for workload routing decisions and Scope 2 reporting workflows. "
        "Live grid data sourced from Electricity Maps when API key configured."
    )

    pdf.section("Disclaimer")
    pdf.body(
        "This report is generated by the EcoRouter digital twin simulation platform. "
        "Validate against your cloud provider billing and official ESG audit processes "
        "before regulatory submission."
    )

    out = BytesIO()
    pdf.output(out)
    return out.getvalue()
